language: c
compiler: gcc
 
jobs:
    include:
        - os: linux
          dist: xenial
          arch: amd64

        - os: linux
          dist: bionic
          arch: amd64

        - os: linux
          dist: focal
          arch: amd64

script:
    - make
    - ./test | grep 'Encrypted: 60 C6 C8 DE 7F 78 D3 C3'
    - ./test | grep 'Decrypted: ABCDEFGH'

 
